---
# Include OS-specific vars
- name: Include os_family vars
  include_vars: "{{ ansible_os_family }}.yml"
  tags: always

# Iterate through list of deployments
- include: az-deploy.yml
  vars:
    az_deploy_name: "{{ item.name }}"
    az_deploy_url: "{{ item.url }}"
    az_deploy_params: "{{ item.params }}"
    az_deploy_subscriptionId: "{{ item.subscriptionId }}"
    az_deploy_location: "{{ item.location }}"
    az_deploy_resgroup: "{{ item.resgroup }}"
  with_items: "{{ az_builder_deployments }}"
  loop_control:
    label: "{{ item.name }}"
  tags: deploy-on-azure
